### ISSUE TITLE
页面打不开

### ISSUE THREAD

**Issue by rockts** [jackchen0120/todo-nodejs-api#3]
请问您这个代码，还需要什么支持吗？
我浏览器访问直接打不开

**Comment by jackchen0120** [comment]
这个是API接口源码，启动有没报错，如果没报错，可以用postman测试一下接口是否正常

**Comment by rockts** [comment]
怎么测试，也没有数据库模。 不知道您的数据库结构啊 api 获取不到啊

**Comment by jackchen0120** [comment]
关注 我的公众号：懒人码农

**Comment by jackchen0120** [comment]
回复：‘’todo‘’ 关键词，即可获取完整的表结构

**Comment by jackchen0120** [comment]
关注我的公众号：懒人码农   回复 ‘’todo‘’ 关键词，即可获取完整的表结构
