### ISSUE TITLE
刚开始学习，觉得老哥写的很好，可能是我太菜了，本地的跑不起来

### ISSUE THREAD

**Issue by MLY123** [jackchen0120/todo-nodejs-api#5]

**Comment by MLY123** [comment]
npm install 之后 npm run start 界面就是这样
![截屏2020-11-26 下午5 00 34](https://user-images.githubusercontent.com/15358816/100329659-f1d3e700-3008-11eb-866a-3921a26f922d.png)

**Comment by jackchen0120** [comment]
有报什么错没

**Comment by jackchen0120** [comment]
你可以看下代码配置了路由地址，去访问试试

**Comment by MLY123** [comment]
就报这样的错误[
![image](https://user-images.githubusercontent.com/15358816/100580544-14277680-3321-11eb-9b55-eac1fff3255e.png)
](url)

**Comment by hornetbillow** [comment]
建议你使用yarn先将版本锁定住，npm缺点太明显了，版本每次拉取都是最新版本

**Comment by jackchen0120** [comment]
> 就报这样的错误[ ![image](https://user-images.githubusercontent.com/15358816/100580544-14277680-3321-11eb-9b55-eac1fff3255e.png) ](url)

抱歉，现在才看到，你这边解决了没

**Comment by wulinjie122** [comment]
我也是一样的问题，压根就跑不起来。
